browser=chrome
timeout=10
baseUrl=file:///C:/Users/USHASRI/.gemini/antigravity/scratch/WebGuard/aut/index.html
registerUrl=file:///C:/Users/USHASRI/.gemini/antigravity/scratch/WebGuard/aut/register.html
forgotUrl=file:///C:/Users/USHASRI/.gemini/antigravity/scratch/WebGuard/aut/forgot.html
dashboardUrl=file:///C:/Users/USHASRI/.gemini/antigravity/scratch/WebGuard/aut/dashboard.html
